# This worflow is composed of two jobs: hardhat and audit:
# - The linter job checks the files linting (typescript, solidity, etc.).
# - The test job compiles and tests the smart contracts.
# - The audit job installs python, slither-analizer and mythril before performing static analysis on solidity files.
name: Smart Contracts CI Workflow

on:
  push:
    paths:
      # Workflows.
      - ".github/workflows/**.yml"
      # Contracts.
      - "contracts/contracts/**.sol"
      # Scripts.
      - "contracts/scripts/**.ts"
      - "contracts/test/**.ts"
      # Configuration files.
      - "contracts/hardhat.config.ts"
      - "contracts/helper.config.ts"
      # Dependencies.
      - "contracts/package.json"
      - "contracts/package-lock.json"

defaults:
  run:
    working-directory: ./contracts

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 📦 Use Node.js v16.14.2 (LTS)
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
          cache: "npm"
          cache-dependency-path: contracts/package-lock.json
      - name: 🔧 Install dependencies
        run: npm install
      - name: 🪄 Lint files with eslint
        run: npx eslint '**/*.{js,ts}'
      - name: 🪄 Lint files with prettier
        run: npx prettier '**/*.{json,sol,md}' --check
      - name: 🪄 Lint files with solhint
        run: npx solhint 'contracts/**/*.sol'

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: 📦 Use Node.js v16.14.2 (LTS)
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
          cache: "npm"
          cache-dependency-path: contracts/package-lock.json
      - name: 🔧 Install npm dependencies
        run: npm install
      - name: 🔧 Install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: 🔧 Setup foundry
        run: forge init --no-commit --no-git --force
      - name: ⚙️ Compile (hardhat)
        run: npx hardhat compile
      - name: ⚙️ Compile (foundry)
        run: forge build
      - name: 🧪 Test (hardhat)
        run: npx hardhat test
      - name: 🧪 Test (foundry)
        run: forge test -vvv --gas-report
      - name: 📊 Coverage (hardhat)
        run: npx hardhat coverage
    env:
      REPORT_GAS: true
      COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}

  audit:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v3
      - name: 📦 Use Node.js v16.14.2 (LTS)
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
          cache: "npm"
          cache-dependency-path: contracts/package-lock.json
      - name: 🔧 Install dependencies
        run: npm install
      - name: 🔧 Install python
        uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: 🔧 Install slither and mythril
        run: |
          python -m pip install --upgrade pip
          pip3 install slither-analyzer mythril
      - name: 🔧 Install solc
        run: |
          sudo wget -O /usr/bin/solc https://github.com/ethereum/solidity/releases/download/v0.8.7/solc-static-linux
          sudo chmod +x /usr/bin/solc
      - name: ⚙️ Compile
        run: npx hardhat compile
      - name: 🐍 Run slither
        run: slither .
      - name: 🛡️ Run mythril
        run: myth analyze contracts/ONS.sol
